name: wound_repository
description: The Repo that handles wound images and bounding boxes
publish_to: "none"
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.7

  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true